artifact_location: file:///Users/huizhang/Documents/GitHub/CNN-Learning-Journey/03_experiment_management/02_MLflow/ml-runs/0
creation_time: 1776909920353
experiment_id: '0'
last_update_time: 1776909920353
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
