seed_everything: 42

trainer:
  max_epochs: 40
  max_steps: -1
  accelerator: gpu
  devices: 1
  precision: bf16-mixed
  deterministic: true
  log_every_n_steps: 10
  enable_model_summary: false
  enable_checkpointing: true

  logger:
    class_path: lightning.pytorch.loggers.MLFlowLogger
    init_args:
      experiment_name: lr_test
      tracking_uri: sqlite:///mlflow.db
      run_name: "1e-1"        

  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch

    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./logs/checkpoints
        monitor: val_acc
        filename: checkpoint_1e-1_{epoch:02d}_{val_acc:.4f}
        save_top_k: 1
        mode: max
        save_last: false

    - class_path: hyperparameters_flower.ProgressiveBackboneFinetuning
      init_args:
        unfreeze_at_epoch_1: null
        unfreeze_at_epoch_2: null

    - class_path: hyperparameters_flower.PostFreezeModelSummary
      init_args: {}

  profiler:
    class_path: lightning.pytorch.profilers.SimpleProfiler
    init_args:
      dirpath: ./profiler_output
      filename: prof_logs_1e-1
      extended: true

model:
  learning_rate: 1e-1
  momentum: 0.9 
  weight_decay: 0.0001
  num_classes: 102

data:
  batch_size: 128
  num_workers: 8
  data_path: ../99_flower_data
  image_size: 224

optimizer: torch.optim.SGD